.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "RDPMUX" "1" "February 2016" "Datto Inc" ""
.
.SH "NAME"
\fBrdpmux\fR \- RDP server multiplexer designed to work with virtual machines
.
.SH "SYNOPSIS"
\fBrdpmux\fR \fIOPTIONS\fR \-\-certificate\-dir=\fIpath to cert dir\fR
.
.SH "DESCRIPTION"
RDPMux is a program designed to provide an RDP frontend to virtual machines\. It currently supports viewing the guest, sending mouse and keyboard input, and literally nothing else\. Many more features are planned, but right now, this project should be considered alpha software\.
.
.P
RDPMux will work fine with multiple virtual machines at once\. It also supports desktop sharing of a kind, in that multiple RDP clients can share the same desktop session\.
.
.P
This manual page is meant to be a terse overview of the various flags and switches you can set\. For complete documentation on RDPMux, please see https://github\.com/datto/rdpmux\.
.
.SH "OPTIONS"
\fB\-v\fR, \fB\-\-v={1,2,3}\fR
.
.IP "" 4
.
.nf

Enable verbose output\. \-\-v (note the two dashes) accepts either 1, 2, or 3 to specify the logging level\. \-v (note the single dash) will enable the most verbose logging available\.
.
.fi
.
.IP "" 0
.
.P
\fB\-\-certificate\-dir=<path to directory containing certificates>\fR
.
.IP "" 4
.
.nf

Specify the path to a directory containing certificates for the RDP connection\. This option is mandatory\.
.
.fi
.
.IP "" 0
.
.P
\fB\-h, \-\-help\fR
.
.IP "" 4
.
.nf

Show brief help output\.
.
.fi
.
.IP "" 0
.
.SH "USAGE"
Using RDPMux is pretty simple\. Start the service, and then start your RDPMux\-aware hypervisor/other backend service\. The two programs should automatically negotiate their internal connection, and RDPMux will start an RDP listener\. Connect to this listener and you should have an RDP session\.
.
.SH "CONSIDERATIONS"
The RDPMux service (and anything that wants to talk to it!) requires access to the DBus system bus in order to work properly\. While it doesn\'t need to be run as root, please ensure that RDPMUx is run in such a way that it has access to the system bus\.
.
.SH "BUGS"
For information on currently open bug reports or if you\'d like to file a bug report, see https://github\.com/datto/rdpmux/issues\.
.
.SH "AUTHOR"
Sri Ramanujam (\fIsramanujam@datto\.com\fR)
.
.SH "COPYRIGHT"
Licensed under Apache 2\.0\.
.
.SH "SEE ALSO"
xfreerdp(1), xrdp(1)
